# Generated by Django 6.0 on 2025-12-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("mesa", models.IntegerField()),
                (
                    "turno",
                    models.CharField(
                        choices=[("DIA", "Día"), ("NOCHE", "Noche")], max_length=5
                    ),
                ),
            ],
        ),
    ]
