# Generated by Django 6.0 on 2025-12-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="comentarios",
            field=models.TextField(blank=True, null=True),
        ),
    ]
