# Generated by Django 6.0 on 2025-12-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_reserva_comentarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="personas",
            field=models.IntegerField(default=1),
        ),
    ]
